
state_codes = [
    'ACT', 'JBT', 'NSW', 'NT', 'QLD',
    'SA', 'TAS', 'VIC', 'WA',
]

state_names = {
    'ACT': 'Australian Capital Territory',
    'JBT': 'Jervis Bay Territory', 
    'NSW': 'New South Wales',
    'NT':  'Northern Territory',
    'QLD': 'Queensland',
    'SA':  'South Australia',
    'TAS': 'Tasmania',
    'VIC': 'Victoria',
    'WA':  'Western Australia',
}

street_addr_suffix = [
    ("ALLEY", "ALY"),
    ("ANEX", "ANX"),
    ("ARCADE", "ARC"),
    ("AVENUE", "AVE"),
    ("BEACH", "BCH"),
    ("BURG", "BG"),
    ("BURGS", "BGS"),
    ("BLUFF", "BLF"),
    ("BLUFFS", "BLFS"),
    ("BOULEVARD", "BLVD"),
    ("BEND", "BND"),
    ("BRANCH", "BR"),
    ("BRIDGE", "BRG"),
    ("BROOK", "BRK"),
    ("BROOKS", "BRKS"),
    ("BOTTOM", "BTM"),
    ("BYPASS", "BYP"),
    ("BAYOU", "BYU"),
    ("CIRCLE", "CIR"),
    ("CIRCLES", "CIRS"),
    ("CLUB", "CLB"),
    ("CLIFF", "CLF"),
    ("CLIFFS", "CLFS"),
    ("COMMON", "CMN"),
    ("COMMONS", "CMNS"),
    ("CORNER", "COR"),
    ("CORNERS", "CORS"),
    ("CAMP", "CP"),
    ("CAPE", "CPE"),
    ("CRESCENT", "CRES"),
    ("CREEK", "CRK"),
    ("COURSE", "CRSE"),
    ("CREST", "CRST"),
    ("CAUSEWAY", "CSWY"),
    ("COURT", "CT"),
    ("CENTER", "CTR"),
    ("CENTERS", "CTRS"),
    ("COURTS", "CTS"),
    ("CURVE ", "CURV"),
    ("COVE", "CV"),
    ("COVES", "CVS"),
    ("CANYON", "CYN"),
    ("DALE", "DL"),
    ("DAM", "DM"),
    ("DRIVE", "DR"),
    ("DRIVES ", "DRS"),
    ("DIVIDE", "DV"),
    ("ESTATE", "EST"),
    ("ESTATES", "ESTS"),
    ("EXPRESSWAY", "EXPY"),
    ("EXTENSION", "EXT"),
    ("EXTENSIONS", "EXTS"),
    ("FALL", "FALL"),
    ("FIELD", "FLD"),
    ("FIELDS", "FLDS"),
    ("FALLS", "FLS"),
    ("FLAT", "FLT"),
    ("FLATS", "FLTS"),
    ("FORD", "FRD"),
    ("FORDS", "FRDS"),
    ("FORGE", "FRG"),
    ("FORGES", "FRGS"),
    ("FORK", "FRK"),
    ("FORKS", "FRKS"),
    ("FOREST", "FRST"),
    ("FERRY", "FRY"),
    ("FORT", "FT"),
    ("FREEWAY", "FWY"),
    ("GARDEN", "GDN"),
    ("GARDENS", "GDNS"),
    ("GLEN", "GLN"),
    ("GLENS", "GLNS"),
    ("GREEN", "GRN"),
    ("GREENS", "GRNS"),
    ("GROVE", "GRV"),
    ("GROVES", "GRVS"),
    ("GATEWAY", "GTWY"),
    ("HARBOR", "HBR"),
    ("HARBORS", "HBRS"),
    ("HILL", "HL"),
    ("HILLS", "HLS"),
    ("HOLLOW", "HOLW"),
    ("HEIGHTS", "HTS"),
    ("HAVEN", "HVN"),
    ("HIGHWAY", "HWY"),
    ("INLET", "INLT"),
    ("ISLAND", "IS"),
    ("ISLE", "ISLE"),
    ("ISLANDS", "ISS"),
    ("JUNCTION", "JCT"),
    ("JUNCTIONS", "JCTS"),
    ("KNOLL", "KNL "),
    ("KNOLLS", "KNLS"),
    ("KEY", "KY"),
    ("KEYS", "KYS"),
    ("LAND", "LAND"),
    ("LOCK", "LCK"),
    ("LOCKS", "LCKS"),
    ("LODGE", "LDG"),
    ("LOAF", "LF"),
    ("LIGHT", "LGT"),
    ("LIGHTS", "LGTS"),
    ("LAKE", "LK"),
    ("LAKES", "LKS"),
    ("LANE", "LN"),
    ("LANDING", "LNDG"),
    ("LOOP", "LOOP"),
    ("MALL", "MALL"),
    ("MEADOW", "MDW"),
    ("MEADOWS", "MDWS"),
    ("MEWS", "MEWS"),
    ("MILL", "ML"),
    ("MILLS", "MLS"),
    ("MANOR", "MNR"),
    ("MANORS", "MNRS"),
    ("MISSION", "MSN"),
    ("MOUNT", "MT"),
    ("MOUNTAIN", "MTN"),
    ("MOUNTAINS", "MTNS"),
    ("MOTORWAY", "MTWY"),
    ("NECK", "NCK"),
    ("OVERPASS", "OPAS"),
    ("ORCHARD", "ORCH"),
    ("OVAL", "OVAL"),
    ("PARK", "PARK"),
    ("PARKS", "PARK"),
    ("PASS", "PASS"),
    ("PATH", "PATH"),
    ("PIKE", "PIKE"),
    ("PARKWAY", "PKWY"),
    ("PARKWAYS", "PKWY"),
    ("PLACE", "PL"),
    ("PLAIN", "PLN"),
    ("PLAINS", "PLNS"),
    ("PLAZA", "PLZ"),
    ("PINE", "PNE "),
    ("PINES", "PNES"),
    ("PRAIRIE", "PR"),
    ("PORT", "PRT"),
    ("PORTS", "PRTS"),
    ("PASSAGE", "PSGE"),
    ("POINT", "PT"),
    ("POINTS", "PTS"),
    ("RADIAL", "RADL"),
    ("RAMP", "RAMP"),
    ("ROAD", "RD"),
    ("RIDGE", "RDG"),
    ("RIDGES", "RDGS"),
    ("ROADS", "RDS"),
    ("RIVER", "RIV"),
    ("RANCH", "RNCH"),
    ("ROW", "ROW"),
    ("RAPID", "RPD"),
    ("RAPIDS", "RPDS"),
    ("REST", "RST"),
    ("ROUTE", "RTE"),
    ("RUE", "RUE"),
    ("RUN", "RUN"),
    ("SHOAL", "SHL"),
    ("SHOALS", "SHLS"),
    ("SHORE", "SHR"),
    ("SHORES", "SHRS"),
    ("SKYWAY", "SKWY"),
    ("SUMMIT", "SMT"),
    ("SPRING", "SPG"),
    ("SPRINGS", "SPGS"),
    ("SPUR", "SPUR"),
    ("SPURS", "SPUR"),
    ("SQUARE", "SQ"),
    ("SQUARES", "SQS"),
    ("STREET", "ST"),
    ("STATION", "STA"),
    ("STRAVENUE", "STRA"),
    ("STREAM", "STRM"),
    ("STREETS", "STS"),
    ("TERRACE", "TER"),
    ("TURNPIKE", "TPKE"),
    ("TRACK", "TRAK"),
    ("TRACE", "TRCE"),
    ("TRAFFICWAY", "TRFY"),
    ("TRAIL", "TRL"),
    ("TRAILER", "TRLR"),
    ("THROUGHWAY", "TRWY"),
    ("TUNNEL", "TUNL"),
    ("UNION", "UN"),
    ("UNIONS", "UNS"),
    ("UNDERPASS", "UPAS"),
    ("VIADUCT", "VIA"),
    ("VISTA", "VIS"),
    ("VILLE", "VL"),
    ("VILLAGE", "VLG"),
    ("VILLAGES", "VLGS"),
    ("VALLEY", "VLY"),
    ("VALLEYS", "VLYS"),
    ("VIEW", "VW"),
    ("VIEWS", "VWS"),
    ("WALK", "WALK"),
    ("WALKS", "WALK"),
    ("WALL", "WALL"),
    ("WAY", "WAY"),
    ("WAYS", "WAYS"),
    ("WELL", "WL "),
    ("WELLS", "WLS"),
    ("CROSSING", "XING"),
    ("CROSSROAD", "XRD"),
    ("CROSSROADS", "XRDS"),
]